import { Select2Option } from '@/components/Select2Search';

export const ALL_WORLD_CURRENCIES: Select2Option[] = [
  { value: 'MYR', label: 'MYR — Malaysian Ringgit', subLabel: 'Malaysia', badge: 'RM' },
  { value: 'USD', label: 'USD — US Dollar', subLabel: 'United States', badge: '$' },
  { value: 'SGD', label: 'SGD — Singapore Dollar', subLabel: 'Singapore', badge: 'S$' },
  { value: 'EUR', label: 'EUR — Euro', subLabel: 'European Union', badge: '€' },
  { value: 'GBP', label: 'GBP — British Pound', subLabel: 'United Kingdom', badge: '£' },
  { value: 'BDT', label: 'BDT — Bangladeshi Taka', subLabel: 'Bangladesh', badge: '৳' },
  { value: 'AED', label: 'AED — UAE Dirham', subLabel: 'United Arab Emirates', badge: 'د.إ' },
  { value: 'SAR', label: 'SAR — Saudi Riyal', subLabel: 'Saudi Arabia', badge: '﷼' },
  { value: 'QAR', label: 'QAR — Qatari Riyal', subLabel: 'Qatar', badge: '﷼' },
  { value: 'KWD', label: 'KWD — Kuwaiti Dinar', subLabel: 'Kuwait', badge: 'د.ك' },
  { value: 'BHD', label: 'BHD — Bahraini Dinar', subLabel: 'Bahrain', badge: '.د.ب' },
  { value: 'OMR', label: 'OMR — Omani Rial', subLabel: 'Oman', badge: '﷼' },
  { value: 'INR', label: 'INR — Indian Rupee', subLabel: 'India', badge: '₹' },
  { value: 'PKR', label: 'PKR — Pakistani Rupee', subLabel: 'Pakistan', badge: '₨' },
  { value: 'LKR', label: 'LKR — Sri Lankan Rupee', subLabel: 'Sri Lanka', badge: 'Rs' },
  { value: 'NPR', label: 'NPR — Nepalese Rupee', subLabel: 'Nepal', badge: 'Rs' },
  { value: 'IDR', label: 'IDR — Indonesian Rupiah', subLabel: 'Indonesia', badge: 'Rp' },
  { value: 'THB', label: 'THB — Thai Baht', subLabel: 'Thailand', badge: '฿' },
  { value: 'VND', label: 'VND — Vietnamese Dong', subLabel: 'Vietnam', badge: '₫' },
  { value: 'PHP', label: 'PHP — Philippine Peso', subLabel: 'Philippines', badge: '₱' },
  { value: 'JPY', label: 'JPY — Japanese Yen', subLabel: 'Japan', badge: '¥' },
  { value: 'CNY', label: 'CNY — Chinese Yuan', subLabel: 'China', badge: '¥' },
  { value: 'HKD', label: 'HKD — Hong Kong Dollar', subLabel: 'Hong Kong', badge: 'HK$' },
  { value: 'TWD', label: 'TWD — New Taiwan Dollar', subLabel: 'Taiwan', badge: 'NT$' },
  { value: 'KRW', label: 'KRW — South Korean Won', subLabel: 'South Korea', badge: '₩' },
  { value: 'AUD', label: 'AUD — Australian Dollar', subLabel: 'Australia', badge: 'A$' },
  { value: 'CAD', label: 'CAD — Canadian Dollar', subLabel: 'Canada', badge: 'C$' },
  { value: 'NZD', label: 'NZD — New Zealand Dollar', subLabel: 'New Zealand', badge: 'NZ$' },
  { value: 'CHF', label: 'CHF — Swiss Franc', subLabel: 'Switzerland', badge: 'CHF' },
  { value: 'ZAR', label: 'ZAR — South African Rand', subLabel: 'South Africa', badge: 'R' },
  { value: 'TRY', label: 'TRY — Turkish Lira', subLabel: 'Turkey', badge: '₺' },
  { value: 'BND', label: 'BND — Brunei Dollar', subLabel: 'Brunei', badge: 'B$' },
  { value: 'EGP', label: 'EGP — Egyptian Pound', subLabel: 'Egypt', badge: 'E£' },
  { value: 'RUB', label: 'RUB — Russian Ruble', subLabel: 'Russia', badge: '₽' },
  { value: 'BRL', label: 'BRL — Brazilian Real', subLabel: 'Brazil', badge: 'R$' },
  { value: 'MXN', label: 'MXN — Mexican Peso', subLabel: 'Mexico', badge: 'Mex$' },
  { value: 'SEK', label: 'SEK — Swedish Krona', subLabel: 'Sweden', badge: 'kr' },
  { value: 'NOK', label: 'NOK — Norwegian Krone', subLabel: 'Norway', badge: 'kr' },
  { value: 'DKK', label: 'DKK — Danish Krone', subLabel: 'Denmark', badge: 'kr' },
  { value: 'PLN', label: 'PLN — Polish Zloty', subLabel: 'Poland', badge: 'zł' },
  { value: 'CZK', label: 'CZK — Czech Koruna', subLabel: 'Czech Republic', badge: 'Kč' },
  { value: 'HUF', label: 'HUF — Hungarian Forint', subLabel: 'Hungary', badge: 'Ft' },
  { value: 'RON', label: 'RON — Romanian Leu', subLabel: 'Romania', badge: 'lei' },
  { value: 'ILS', label: 'ILS — Israeli Shekel', subLabel: 'Israel', badge: '₪' },
  { value: 'NGN', label: 'NGN — Nigerian Naira', subLabel: 'Nigeria', badge: '₦' },
  { value: 'KES', label: 'KES — Kenyan Shilling', subLabel: 'Kenya', badge: 'KSh' },
  { value: 'CLP', label: 'CLP — Chilean Peso', subLabel: 'Chile', badge: 'CLP$' },
  { value: 'COP', label: 'COP — Colombian Peso', subLabel: 'Colombia', badge: 'COL$' },
  { value: 'PEN', label: 'PEN — Peruvian Sol', subLabel: 'Peru', badge: 'S/' },
  { value: 'ARS', label: 'ARS — Argentine Peso', subLabel: 'Argentina', badge: '$' },
  { value: 'KZT', label: 'KZT — Kazakhstani Tenge', subLabel: 'Kazakhstan', badge: '₸' },
  { value: 'UZS', label: 'UZS — Uzbekistani Som', subLabel: 'Uzbekistan', badge: 'so\'m' },
];
