import { Select2Option } from '@/components/Select2Search';

export const ALL_WORLD_LANGUAGES: Select2Option[] = [
  // --- South & Southeast Asia (Primary Migration & Regional Hubs) ---
  { value: 'English', label: 'English', subLabel: 'Global / US / UK / Canada / Australia', badge: 'EN' },
  { value: 'Bahasa Melayu', label: 'Bahasa Melayu (Malay)', subLabel: 'Malaysia / Brunei / Singapore', badge: 'MS' },
  { value: 'Bengali', label: 'Bengali (বাংলা)', subLabel: 'Bangladesh / India (West Bengal)', badge: 'BN' },
  { value: 'Chinese (Mandarin)', label: 'Chinese Mandarin (普通话)', subLabel: 'China / Taiwan / Singapore / Malaysia', badge: 'ZH' },
  { value: 'Chinese (Cantonese)', label: 'Chinese Cantonese (粵語)', subLabel: 'Hong Kong / Macau / Guangdong', badge: 'YUE' },
  { value: 'Hindi', label: 'Hindi (हिन्दी)', subLabel: 'India / Fiji / Mauritius', badge: 'HI' },
  { value: 'Tamil', label: 'Tamil (தமிழ்)', subLabel: 'Malaysia / Singapore / India / Sri Lanka', badge: 'TA' },
  { value: 'Urdu', label: 'Urdu (اردو)', subLabel: 'Pakistan / India', badge: 'UR' },
  { value: 'Indonesian', label: 'Indonesian (Bahasa Indonesia)', subLabel: 'Indonesia', badge: 'ID' },
  { value: 'Filipino / Tagalog', label: 'Filipino / Tagalog', subLabel: 'Philippines', badge: 'TL' },
  { value: 'Vietnamese', label: 'Vietnamese (Tiếng Việt)', subLabel: 'Vietnam', badge: 'VI' },
  { value: 'Thai', label: 'Thai (ไทย)', subLabel: 'Thailand', badge: 'TH' },
  { value: 'Burmese', label: 'Burmese (မြန်မာစာ)', subLabel: 'Myanmar', badge: 'MY' },
  { value: 'Nepali', label: 'Nepali (नेपाली)', subLabel: 'Nepal / India / Bhutan', badge: 'NE' },
  { value: 'Sinhala', label: 'Sinhala (සිංහල)', subLabel: 'Sri Lanka', badge: 'SI' },
  { value: 'Khmer', label: 'Khmer (ភាសាខ្មែរ)', subLabel: 'Cambodia', badge: 'KM' },
  { value: 'Lao', label: 'Lao (ພາສາລາວ)', subLabel: 'Laos', badge: 'LO' },
  { value: 'Dzongkha', label: 'Dzongkha (རྫོང་ཁ)', subLabel: 'Bhutan', badge: 'DZ' },
  { value: 'Dhivehi', label: 'Dhivehi (ދިވެހި)', subLabel: 'Maldives', badge: 'DV' },
  { value: 'Tetum', label: 'Tetum (Lia-Tetun)', subLabel: 'East Timor (Timor-Leste)', badge: 'TET' },

  // --- Indian Subcontinent Regional Languages ---
  { value: 'Punjabi', label: 'Punjabi (ਪੰਜਾਬੀ / پنجابی)', subLabel: 'Pakistan / India', badge: 'PA' },
  { value: 'Telugu', label: 'Telugu (తెలుగు)', subLabel: 'India (Andhra / Telangana)', badge: 'TE' },
  { value: 'Marathi', label: 'Marathi (मराठी)', subLabel: 'India (Maharashtra)', badge: 'MR' },
  { value: 'Gujarati', label: 'Gujarati (ગુજરાતી)', subLabel: 'India (Gujarat)', badge: 'GU' },
  { value: 'Malayalam', label: 'Malayalam (മലയാളം)', subLabel: 'India (Kerala)', badge: 'ML' },
  { value: 'Kannada', label: 'Kannada (ಕನ್ನಡ)', subLabel: 'India (Karnataka)', badge: 'KN' },
  { value: 'Odia', label: 'Odia (ଓଡ଼ିଆ)', subLabel: 'India (Odisha)', badge: 'OR' },
  { value: 'Assamese', label: 'Assamese (অসমীয়া)', subLabel: 'India (Assam)', badge: 'AS' },
  { value: 'Sindhi', label: 'Sindhi (سنڌي)', subLabel: 'Pakistan / India', badge: 'SD' },
  { value: 'Pashto', label: 'Pashto (پښتو)', subLabel: 'Afghanistan / Pakistan', badge: 'PS' },
  { value: 'Balochi', label: 'Balochi (بلوچی)', subLabel: 'Pakistan / Iran', badge: 'BAL' },

  // --- East Asia ---
  { value: 'Japanese', label: 'Japanese (日本語)', subLabel: 'Japan', badge: 'JA' },
  { value: 'Korean', label: 'Korean (한국어)', subLabel: 'South Korea / North Korea', badge: 'KO' },
  { value: 'Mongolian', label: 'Mongolian (Монгол хэл)', subLabel: 'Mongolia', badge: 'MN' },
  { value: 'Tibetan', label: 'Tibetan (བོད་སྐད་)', subLabel: 'Tibet / China / Nepal / India', badge: 'BO' },

  // --- Middle East & North Africa (MENA) ---
  { value: 'Arabic', label: 'Arabic (العربية)', subLabel: 'Saudi Arabia / UAE / Qatar / Egypt / Middle East', badge: 'AR' },
  { value: 'Persian / Farsi', label: 'Persian / Farsi (فارسی)', subLabel: 'Iran', badge: 'FA' },
  { value: 'Dari', label: 'Dari (دری)', subLabel: 'Afghanistan', badge: 'PRS' },
  { value: 'Turkish', label: 'Turkish (Türkçe)', subLabel: 'Turkey / Cyprus', badge: 'TR' },
  { value: 'Hebrew', label: 'Hebrew (עברית)', subLabel: 'Israel', badge: 'HE' },
  { value: 'Kurdish', label: 'Kurdish (Kurdî / کوردی)', subLabel: 'Iraq / Turkey / Iran / Syria', badge: 'KU' },
  { value: 'Azerbaijani', label: 'Azerbaijani (Azərbaycan)', subLabel: 'Azerbaijan / Iran', badge: 'AZ' },

  // --- Central Asia ---
  { value: 'Uzbek', label: 'Uzbek (Oʻzbekcha)', subLabel: 'Uzbekistan', badge: 'UZ' },
  { value: 'Kazakh', label: 'Kazakh (Қазақша)', subLabel: 'Kazakhstan', badge: 'KK' },
  { value: 'Kyrgyz', label: 'Kyrgyz (Кыргызча)', subLabel: 'Kyrgyzstan', badge: 'KY' },
  { value: 'Tajik', label: 'Tajik (Тоҷикӣ)', subLabel: 'Tajikistan', badge: 'TG' },
  { value: 'Turkmen', label: 'Turkmen (Türkmençe)', subLabel: 'Turkmenistan', badge: 'TK' },

  // --- Europe: Western, Central & Northern ---
  { value: 'German', label: 'German (Deutsch)', subLabel: 'Germany / Austria / Switzerland / Liechtenstein', badge: 'DE' },
  { value: 'French', label: 'French (Français)', subLabel: 'France / Belgium / Switzerland / Monaco / Canada', badge: 'FR' },
  { value: 'Spanish', label: 'Spanish (Español)', subLabel: 'Spain / Mexico / Argentina / Colombia / Latin America', badge: 'ES' },
  { value: 'Italian', label: 'Italian (Italiano)', subLabel: 'Italy / Switzerland / San Marino / Vatican', badge: 'IT' },
  { value: 'Portuguese', label: 'Portuguese (Português)', subLabel: 'Portugal / Brazil / Angola / Mozambique', badge: 'PT' },
  { value: 'Dutch', label: 'Dutch (Nederlands)', subLabel: 'Netherlands / Belgium (Flanders) / Suriname', badge: 'NL' },
  { value: 'Swedish', label: 'Swedish (Svenska)', subLabel: 'Sweden / Finland', badge: 'SV' },
  { value: 'Danish', label: 'Danish (Dansk)', subLabel: 'Denmark / Greenland / Faroe Islands', badge: 'DA' },
  { value: 'Norwegian', label: 'Norwegian (Norsk)', subLabel: 'Norway', badge: 'NO' },
  { value: 'Finnish', label: 'Finnish (Suomi)', subLabel: 'Finland', badge: 'FI' },
  { value: 'Icelandic', label: 'Icelandic (Íslenska)', subLabel: 'Iceland', badge: 'IS' },
  { value: 'Irish', label: 'Irish (Gaeilge)', subLabel: 'Ireland', badge: 'GA' },
  { value: 'Welsh', label: 'Welsh (Cymraeg)', subLabel: 'United Kingdom (Wales)', badge: 'CY' },
  { value: 'Scottish Gaelic', label: 'Scottish Gaelic (Gàidhlig)', subLabel: 'United Kingdom (Scotland)', badge: 'GD' },
  { value: 'Luxembourgish', label: 'Luxembourgish (Lëtzebuergesch)', subLabel: 'Luxembourg', badge: 'LB' },
  { value: 'Maltese', label: 'Maltese (Malti)', subLabel: 'Malta', badge: 'MT' },
  { value: 'Catalan', label: 'Catalan (Català)', subLabel: 'Spain (Catalonia) / Andorra', badge: 'CA' },
  { value: 'Basque', label: 'Basque (Euskara)', subLabel: 'Spain / France (Basque Country)', badge: 'EU' },
  { value: 'Galician', label: 'Galician (Galego)', subLabel: 'Spain (Galicia)', badge: 'GL' },

  // --- Europe: Eastern & Southeastern ---
  { value: 'Russian', label: 'Russian (Русский)', subLabel: 'Russia / Belarus / Central Asia', badge: 'RU' },
  { value: 'Ukrainian', label: 'Ukrainian (Українська)', subLabel: 'Ukraine', badge: 'UK' },
  { value: 'Polish', label: 'Polish (Polski)', subLabel: 'Poland', badge: 'PL' },
  { value: 'Czech', label: 'Czech (Čeština)', subLabel: 'Czech Republic (Czechia)', badge: 'CS' },
  { value: 'Slovak', label: 'Slovak (Slovenčina)', subLabel: 'Slovakia', badge: 'SK' },
  { value: 'Hungarian', label: 'Hungarian (Magyar)', subLabel: 'Hungary', badge: 'HU' },
  { value: 'Romanian', label: 'Romanian (Română)', subLabel: 'Romania / Moldova', badge: 'RO' },
  { value: 'Bulgarian', label: 'Bulgarian (Български)', subLabel: 'Bulgaria', badge: 'BG' },
  { value: 'Greek', label: 'Greek (Ελληνικά)', subLabel: 'Greece / Cyprus', badge: 'EL' },
  { value: 'Serbian', label: 'Serbian (Српски)', subLabel: 'Serbia / Bosnia / Montenegro', badge: 'SR' },
  { value: 'Croatian', label: 'Croatian (Hrvatski)', subLabel: 'Croatia / Bosnia', badge: 'HR' },
  { value: 'Bosnian', label: 'Bosnian (Bosanski)', subLabel: 'Bosnia and Herzegovina', badge: 'BS' },
  { value: 'Montenegrin', label: 'Montenegrin (Crnogorski)', subLabel: 'Montenegro', badge: 'CNR' },
  { value: 'Slovenian', label: 'Slovenian (Slovenščina)', subLabel: 'Slovenia', badge: 'SL' },
  { value: 'Albanian', label: 'Albanian (Shqip)', subLabel: 'Albania / Kosovo / North Macedonia', badge: 'SQ' },
  { value: 'Macedonian', label: 'Macedonian (Македонски)', subLabel: 'North Macedonia', badge: 'MK' },
  { value: 'Belarusian', label: 'Belarusian (Беларуская)', subLabel: 'Belarus', badge: 'BE' },
  { value: 'Lithuanian', label: 'Lithuanian (Lietuvių)', subLabel: 'Lithuania', badge: 'LT' },
  { value: 'Latvian', label: 'Latvian (Latviešu)', subLabel: 'Latvia', badge: 'LV' },
  { value: 'Estonian', label: 'Estonian (Eesti)', subLabel: 'Estonia', badge: 'ET' },
  { value: 'Georgian', label: 'Georgian (ქართული)', subLabel: 'Georgia', badge: 'KA' },
  { value: 'Armenian', label: 'Armenian (Հայերեն)', subLabel: 'Armenia', badge: 'HY' },

  // --- Sub-Saharan Africa ---
  { value: 'Swahili', label: 'Swahili (Kiswahili)', subLabel: 'Kenya / Tanzania / Uganda / Rwanda / DR Congo', badge: 'SW' },
  { value: 'Amharic', label: 'Amharic (አማርኛ)', subLabel: 'Ethiopia', badge: 'AM' },
  { value: 'Oromo', label: 'Oromo (Afaan Oromoo)', subLabel: 'Ethiopia / Kenya', badge: 'OM' },
  { value: 'Tigrinya', label: 'Tigrinya (ትግርኛ)', subLabel: 'Eritrea / Ethiopia', badge: 'TI' },
  { value: 'Somali', label: 'Somali (Soomaaliga)', subLabel: 'Somalia / Djibouti / Ethiopia / Kenya', badge: 'SO' },
  { value: 'Hausa', label: 'Hausa (Harshen Hausa)', subLabel: 'Nigeria / Niger / Ghana', badge: 'HA' },
  { value: 'Yoruba', label: 'Yoruba (Èdè Yorùbá)', subLabel: 'Nigeria / Benin / Togo', badge: 'YO' },
  { value: 'Igbo', label: 'Igbo (Asụsụ Igbo)', subLabel: 'Nigeria', badge: 'IG' },
  { value: 'Zulu', label: 'Zulu (isiZulu)', subLabel: 'South Africa', badge: 'ZU' },
  { value: 'Xhosa', label: 'Xhosa (isiXhosa)', subLabel: 'South Africa', badge: 'XH' },
  { value: 'Afrikaans', label: 'Afrikaans', subLabel: 'South Africa / Namibia', badge: 'AF' },
  { value: 'Sesotho', label: 'Sesotho (Southern Sotho)', subLabel: 'Lesotho / South Africa', badge: 'ST' },
  { value: 'Setswana', label: 'Setswana (Tswana)', subLabel: 'Botswana / South Africa', badge: 'TN' },
  { value: 'Shona', label: 'Shona (chiShona)', subLabel: 'Zimbabwe', badge: 'SN' },
  { value: 'Kinyarwanda', label: 'Kinyarwanda', subLabel: 'Rwanda', badge: 'RW' },
  { value: 'Kirundi', label: 'Kirundi', subLabel: 'Burundi', badge: 'RN' },
  { value: 'Lingala', label: 'Lingala', subLabel: 'DR Congo / Republic of the Congo', badge: 'LN' },
  { value: 'Wolof', label: 'Wolof', subLabel: 'Senegal / Gambia / Mauritania', badge: 'WO' },
  { value: 'Malagasy', label: 'Malagasy', subLabel: 'Madagascar', badge: 'MG' },
  { value: 'Chewa / Nyanja', label: 'Chewa (Chichewa / Nyanja)', subLabel: 'Malawi / Zambia / Mozambique', badge: 'NY' },
  { value: 'Akan / Twi', label: 'Akan / Twi', subLabel: 'Ghana', badge: 'AK' },
  { value: 'Luganda', label: 'Luganda (Ganda)', subLabel: 'Uganda', badge: 'LG' },
  { value: 'Mauritian Creole', label: 'Mauritian Creole (Kreol Morisien)', subLabel: 'Mauritius', badge: 'MFE' },

  // --- Americas (Latin America, Caribbean & Indigenous) ---
  { value: 'Haitian Creole', label: 'Haitian Creole (Kreyòl Ayisyen)', subLabel: 'Haiti / Dominican Republic', badge: 'HT' },
  { value: 'Papiamento', label: 'Papiamento', subLabel: 'Aruba / Curaçao / Bonaire', badge: 'PAP' },
  { value: 'Quechua', label: 'Quechua (Runasimi)', subLabel: 'Peru / Bolivia / Ecuador', badge: 'QU' },
  { value: 'Guarani', label: 'Guarani (Avañeʼẽ)', subLabel: 'Paraguay / Argentina / Bolivia', badge: 'GN' },
  { value: 'Aymara', label: 'Aymara (Aymar aru)', subLabel: 'Bolivia / Peru / Chile', badge: 'AY' },

  // --- Oceania & Pacific Islands ---
  { value: 'Maori', label: 'Maori (Te Reo Māori)', subLabel: 'New Zealand', badge: 'MI' },
  { value: 'Fijian', label: 'Fijian (Na Vosa Vakaviti)', subLabel: 'Fiji', badge: 'FJ' },
  { value: 'Fiji Hindi', label: 'Fiji Hindi (फ़िजी बात)', subLabel: 'Fiji', badge: 'HIF' },
  { value: 'Samoan', label: 'Samoan (Gagana Sāmoa)', subLabel: 'Samoa / American Samoa', badge: 'SM' },
  { value: 'Tongan', label: 'Tongan (Lea Fakatonga)', subLabel: 'Tonga', badge: 'TO' },
  { value: 'Tok Pisin', label: 'Tok Pisin', subLabel: 'Papua New Guinea', badge: 'TPI' },
  { value: 'Bislama', label: 'Bislama', subLabel: 'Vanuatu', badge: 'BI' },
  { value: 'Chamorro', label: 'Chamorro (Finuʼ Chamoru)', subLabel: 'Guam / Northern Mariana Islands', badge: 'CH' },
  { value: 'Hawaiian', label: 'Hawaiian (ʻŌlelo Hawaiʻi)', subLabel: 'United States (Hawaii)', badge: 'HAW' },
];
